project_name      = "platform"
environment       = "dev"
location          = "westeurope"
key_vault_name    = "kv-platform-dev-plc"
keyvault_location = "polandcentral"
acr_name          = "acrplatformdevplc"